// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package athletes

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID         pgtype.UUID
	CreateTime pgtype.Timestamptz
	Name       string
	AthleteID  pgtype.UUID
}

type Athlete struct {
	ID         pgtype.UUID
	CreateTime pgtype.Timestamptz
	Name       string
}

type BloodLactateMeasure struct {
	ID           pgtype.UUID
	CreateTime   pgtype.Timestamptz
	ActivityID   pgtype.UUID
	MmolPerLiter pgtype.Numeric
	HeartRateBpm int32
}
