// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package athletes

import (
	"time"

	"github.com/jackc/pgtype"
)

type Activity struct {
	ID         pgtype.UUID
	CreateTime time.Time
	Name       string
	AthleteID  pgtype.UUID
}

type Athlete struct {
	ID         pgtype.UUID
	CreateTime time.Time
	Name       string
}

type BloodLactateMeasure struct {
	ID           pgtype.UUID
	CreateTime   time.Time
	ActivityID   pgtype.UUID
	MmolPerLiter string
	HeartRateBpm int16
}
