// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package athletes

import (
	"context"

	"github.com/jackc/pgtype"
)

type Querier interface {
	AddActivity(ctx context.Context, arg AddActivityParams) (Activity, error)
	AddAthlete(ctx context.Context, name string) (Athlete, error)
	AddMeasure(ctx context.Context, arg AddMeasureParams) (BloodLactateMeasure, error)
	DeleteAthlete(ctx context.Context, id pgtype.UUID) (Athlete, error)
}

var _ Querier = (*Queries)(nil)
