// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: oidc.sql

package internal

import (
	"context"
)

const createOIDCUser = `-- name: CreateOIDCUser :one
insert into oidc_users (subject) values ($1) returning id, subject
`

func (q *Queries) CreateOIDCUser(ctx context.Context, subject string) (*OIDCUser, error) {
	row := q.db.QueryRow(ctx, createOIDCUser, subject)
	var i OIDCUser
	err := row.Scan(&i.ID, &i.Subject)
	return &i, err
}

const getOIDCUser = `-- name: GetOIDCUser :one
select id, subject from oidc_users where subject = $1
`

func (q *Queries) GetOIDCUser(ctx context.Context, subject string) (*OIDCUser, error) {
	row := q.db.QueryRow(ctx, getOIDCUser, subject)
	var i OIDCUser
	err := row.Scan(&i.ID, &i.Subject)
	return &i, err
}
