// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: oidc.sql

package internal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCUser = `-- name: CreateOIDCUser :one
insert into oidc_users (subject) values ($1) on conflict (subject) do update set subject=excluded.subject returning id, subject
`

func (q *Queries) CreateOIDCUser(ctx context.Context, subject string) (*OIDCUser, error) {
	row := q.db.QueryRow(ctx, createOIDCUser, subject)
	var i OIDCUser
	err := row.Scan(&i.ID, &i.Subject)
	return &i, err
}

const getOIDCUser = `-- name: GetOIDCUser :one
select id, subject from oidc_users where id = $1
`

func (q *Queries) GetOIDCUser(ctx context.Context, id pgtype.UUID) (*OIDCUser, error) {
	row := q.db.QueryRow(ctx, getOIDCUser, id)
	var i OIDCUser
	err := row.Scan(&i.ID, &i.Subject)
	return &i, err
}
