// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, oidcSubject string) (User, error)
}

var _ Querier = (*Queries)(nil)
