// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"context"
)

type Querier interface {
	// Note: we don't actually need to update anything, but if we don't,
	// the query doesn't return the row.
	GetUser(ctx context.Context, oidcSubject string) (User, error)
}

var _ Querier = (*Queries)(nil)
