// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package users

import (
	"context"
)

const getUser = `-- name: GetUser :one
INSERT INTO users (
  oidc_subject
) VALUES (
  $1
)
ON CONFLICT (oidc_subject) DO UPDATE set oidc_subject = EXCLUDED.oidc_subject
RETURNING id, create_time, oidc_subject
`

func (q *Queries) GetUser(ctx context.Context, oidcSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, oidcSubject)
	var i User
	err := row.Scan(&i.ID, &i.CreateTime, &i.OidcSubject)
	return i, err
}
